name: MailMe
version: ${project.version}
main: me.harry0198.mailme.MailMe
api-version: 1.13
authors: [Harry0198]
description: This plugin allows players to transfer items, messages, sounds, locations and etc to each other accross the waves!

commands:
  mail:

